<?php include "./views/header.phtml"; ?>

<div class="container" style="width: 1100px; padding-top: 4%;">
<!DOCTYPE HTML>
<html>
<head>
<style>
.error {color: #FF0000;}
#example1 {
    border: 3px solid coral;
    padding: 10px;
    border-radius: 25px;
}
</style>
</head>
<body>

<?php
// define variables and set to empty values
$name = $address = $road = $payor = $website = $date = "";

?>
<h2><center>ใบสำคัญรับเงิน</center></h2>
<div id="example1">
<p><span class="error">กรุณากรอกข้อมูลให้ครบถ้วน</span></p>
<form>
  <div>
    <label for="date">วันที่-เดือน-ปี:</label>
    <input type="date" id="date" name="date" value="<?php echo $date;?>"><br><br>
  </div>
</form>

  <form method="post" action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]);?>">
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    ชื่อ: <input type="text" name="name" value="<?php echo $name;?>"><br><br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    บ้านเลขที่: <input type="text" name="address" value="<?php echo $address;?>"><br><br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    ถนน: <input type="text" name="road" value="<?php echo $road;?>"><br><br>
    &nbsp;&nbsp;&nbsp;&nbsp;
    ที่ 1: รายการ <input type="text" name="list1" value="<?php echo $list1;?>">
    จำนวน <input type="text" name="address" value="<?php echo $address;?>">
    หน่วยละ <input type="text" name="address" value="<?php echo $address;?>">
    จำนวนเงิน <input type="text" name="address" value="<?php echo $address;?>"><br><br>

    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    ชื่อผู้รับเงิน: <input type="text" name="name" value="<?php echo $name;?>"><br><br>
    &nbsp;&nbsp;&nbsp;
    ชื่อผู้จ่ายเงิน: <input type="text" name="payor" value="<?php echo $payor;?>"><br><br>
    <center><input type="submit" name="submit" value="Submit"></center>
  </form>
</div>
<br>
<div id="example1">
  <center>
    <?php
    echo "<h3>แบบฟอร์มใบสำคัญรับเงิน</h3>";
    ?>
  <img src="./img/01.jpg" width="600" height="700">
</center>
</div>
<br>


</body>
</html>
</div>
