<?php include "./views/header.phtml"; ?>

<!-- Info boxes -->
<section class="content" style="padding-top:3%; font-family: 'Itim', cursive;">
  <div class="container">
  <div class="row">
    <div class="col-12 col-sm-6 col-md-3">
      <div class="info-box">
        <span class="info-box-icon bg-info elevation-1"><i class="fa fa-gear"></i></span>

        <div class="info-box-content">
          <span class="info-box-text">ใบสำคัญรับเงิน</span>
          <span class="info-box-number">
            10 ฉบับ
          </span>
        </div>
        <!-- /.info-box-content -->
      </div>
      <!-- /.info-box -->
    </div>
    <!-- /.col -->
    <div class="col-12 col-sm-6 col-md-3">
      <div class="info-box mb-3">
        <span class="info-box-icon bg-danger elevation-1"><i class="fa fa-google-plus"></i></span>

        <div class="info-box-content">
          <span class="info-box-text">หนังสือราชการ</span>
          <span class="info-box-number">41,410 ฉบับ</span>
        </div>
        <!-- /.info-box-content -->
      </div>
      <!-- /.info-box -->
    </div>
    <!-- /.col -->

    <!-- fix for small devices only -->
    <div class="clearfix hidden-md-up"></div>

    <div class="col-12 col-sm-6 col-md-3">
      <div class="info-box mb-3">
        <span class="info-box-icon bg-success elevation-1"><i class="fa fa-shopping-cart"></i></span>

        <div class="info-box-content">
          <span class="info-box-text">บันทึกข้อความ</span>
          <span class="info-box-number">760 ฉบับ</span>
        </div>
        <!-- /.info-box-content -->
      </div>
      <!-- /.info-box -->
    </div>
    <!-- /.col -->
    <div class="col-12 col-sm-6 col-md-3">
      <div class="info-box mb-3">
        <span class="info-box-icon bg-warning elevation-1"><i class="fa fa-users"></i></span>

        <div class="info-box-content">
          <span class="info-box-text">การอัพโหลด</span>
          <span class="info-box-number">2,000 ครั้ง</span>
        </div>
        <!-- /.info-box-content -->
      </div>
      <!-- /.info-box -->
    </div>
    <!-- /.col -->
  </div>
  <!-- /.row -->
  </div>
</section>


<div class="container" style="padding-top: 1%; padding-bottom: 5%; font-family: 'Itim', cursive;">
<!-- TABLE: LATEST ORDERS -->
  <div class="card">
    <div class="card-header border-transparent">
      <h2 class="card-title">รายการของคุณ</h2>

      <div class="card-tools">
        <button type="button" class="btn btn-tool" data-widget="collapse" data-toggle="collapse" data-target="#table-list">
          <i class="fa fa-minus"></i>
        </button>
        <button type="button" class="btn btn-tool" data-widget="remove" >
          <i class="fa fa-times"></i>
        </button>
      </div>
    </div>
    <!-- /.card-header -->
    <div class="card-body p-0 collapse show" id="table-list">
      <div class="table-responsive">
        <table class="table m-0">
          <thead style="font-size:18px;">
          <tr>
            <th>ชื่อรายการ</th>
            <th>ชื่อไฟล์</th>
            <th>รูปแบบ</th>
            <th>รายละเอียด</th>
          </tr>
          </thead>
          <tbody>
          <?php
          foreach($alldata as $obj) { ?>
          <tr>
            <td><?php echo $obj->name_doc; ?></td>
            <td><a href="./<?php echo $obj->file_path; ?>" onMouseOver="this.style.color='#0F0'" onMouseOut="this.style.color='#00F'" style="color:#00F;"><?php echo $obj->file_name; ?></a></td>
            <td><span class="badge badge-warning">ไฟล์อัพโหลด</span></td>
            <td><?php echo $obj->describ; ?></td>
          </tr>
          <?php
            }
          ?>
          </tbody>
        </table>
      </div>
      <!-- /.table-responsive -->
    </div>

    <!-- /.card-body -->
    <div class="card-footer clearfix">
      <a href="./pdfmake" class="btn btn-sm btn-info float-left">สร้างเอกสาร PDF</a>
      <a href="./upload" class="btn btn-sm btn-info float-left">อัพโหลดไฟล์</a>
      <a href="javascript:void(0)" class="btn btn-sm btn-secondary float-right">View All Orders</a>
    </div>
    <!-- /.card-footer -->
  </div>
  <!-- /.card -->
</div>




<?php include "./views/footer.phtml"; ?>
