<?php
include "./views/header.phtml";
?>
<div class="container" style="margin-top: 3%;margin-bottom: 3%; padding: 2%; border: 2px solid black">
  <form method="post" action="./pdfmake">
    <fieldset><b><h3 style="text-align:center;">บันทึกข้อความ</h3></b></fieldset>
    <hr>
    <div class="row">
      <div class="col-md-12">
          <div class="form-group">
            <label>ส่วนราชการ</label>
            <input type="text" class="form-control" name="mainsection" value="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">
          </div>
      </div>
      <div class="col-md-6">
          <div class="form-group">
            <label>ที่</label>
            <input type="text" class="form-control" name="numberodr" value="yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy">
          </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
         <label >วันที่ เดือน ปี</label>
         <input type="date" name="bday" max="3000-12-31" min="1000-01-01" class="form-control" value="2018-05-17">
        </div>
      </div>
      <div class="col-md-12">
        <div class="form-group">
          <label>เรื่อง</label>
          <input type="text" class="form-control" name="name_stry" value="ขอออกนอกสถานที่">
        </div>
      </div>
      <div class="col-md-12">
        <div class="form-group">
          <label for="comment">ข้อความส่วนเเรก:</label>
          <textarea class="form-control" rows="5" name="firsttmsg" id="comment">Lorem Ipsum คือ เนื้อหาจำลองแบบเรียบๆ ที่ใช้กันในธุรกิจงานพิมพ์หรืองานเรียงพิมพ์ มันได้กลายมาเป็นเนื้อหาจำลองมาตรฐานของธุรกิจดังกล่าวมาตั้งแต่ศตวรรษที่ 16 เมื่อเครื่องพิมพ์โนเนมเครื่องหนึ่งนำรางตัวพิมพ์มาสลับสับตำแหน่งตัวอักษรเพื่อทำหนังสือตัวอย่าง Lorem Ipsum อยู่ยงคงกระพันมาไม่ใช่แค่เพียงห้าศตวรรษ แต่อยู่มาจนถึงยุคที่พลิกโฉมเข้าสู่งานเรียงพิมพ์ด้วยวิธีทางอิเล็กทรอนิกส์ และยังคงสภาพเดิมไว้อย่างไม่มีการเปลี่ยนแปลงมันได้รับความนิยมมากขึ้นในยุค ค.ศ. 1960 เมื่อแผ่น Letraset วางจำหน่ายโดยมีข้อความบนนั้นเป็น Lorem Ipsum และล่าสุดกว่านั้น คือเมื่อซอฟท์แวร์การทำสื่อสิ่งพิมพ์ (Desktop Publishing) อย่าง Aldus PageMaker ได้รวมเอา Lorem Ipsum เวอร์ชั่นต่างๆ เข้าไว้ในซอฟท์แวร์ด้วย
          </textarea>
        </div>
      </div>
      <div class="col-md-12">
        <div class="form-group">
          <label for="comment">ข้อความส่วนสุดท้าย:</label>
          <textarea class="form-control" rows="5" name="lastmsg" id="comment">ด้านล่างของหน้านี้คือท่อนมาตรฐานของ Lorem Ipsum ที่ใช้กันมาตั้งแต่คริสตศตวรรษที่ 16ที่ได้รับการสร้างขึ้นใหม่สำหรับผู้ที่สนใจ ประกอบไปด้วย ตอนที่ 1.10.32 และ 1.10.33 จากเรื่อง "de Finibus Bonorum et Malorum" โดยซิเซโร
          </textarea>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <label>ชื่อ</label>
          <input type="text" class="form-control" name="ownname" value="นายแซม สมิธ">
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <label>ตำแหน่ง</label>
          <input type="text" class="form-control" name="position" value="นักวิชาการคอมพิวเตอร์">
        </div>
      </div>
      <div class="section" style="display:inline;">
        <button type="submit" class="btn btn-primary">ตกลง</button>
        <button type="submit" class="btn btn-danger">ล้างข้อมูล</button>
    </div>
  </form>
</div>
