<?php include "./views/header.phtml"; ?>


<div class="container" style="width: 495px; padding-top: 4%;">

  <div class="card-footer clearfix">
    <a href="./pdfmake" class="btn btn-sm btn-info float-left">ใบสำคัญรับเงิน</a>
    <a href="./upload" class="btn btn-sm btn-info float-center ">หนังสือราชการ</a>
    <a href="./bill" class="btn btn-sm btn-info float-right">บันทึกข้อความ</a>
  </div>

</div>
