<?php include "./views/header.phtml"; ?>
<?php if(!empty($error)) {

  echo '<div class="alert alert-danger" role="alert">This is a danger alert—check it out!</div>';

}  ?>

<?php
if(!empty($success)) { ?>

  <div class="modal-dialog modal-lg" style="padding-top: 5%;">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">เเจ้งเตือน</h4>
        </div>
        <div class="modal-body">
          <p style="font-size:18px;">อัพโหลดสำเร็จ</p>
        </div>
        <div class="modal-footer">
          <a href="./home" style="color:red;">เข้าสู่หน้า Home</a>
        </div>
      </div>
    </div>
  </div>
<?php exit('</body></html>'); } ?>


<div class="container" style="width: 500px; padding-top: 4%;">

  <form method="post" enctype="multipart/form-data" action="./upload">
    <div class="form-group">
      <label for="recipient-name" class="col-form-label">ชื่อเอกสารหรือชื่อเรื่อง:</label>
      <input type="text" name="name_doc" class="form-control" id="recipient-name" value="โครงการ A">
    </div>
    <div class="form-group">
      <label for="message-text" class="col-form-label">รายละเอียด:</label>
      <textarea class="form-control" name="describ" id="message-text">รายละเอียดของโครงการนี้...</textarea>
    </div>
    <div class="form-group">
      <label for="exampleFormControlFile1">ไฟล์ที่อัพโหลด</label>
      <input type="hidden" name="MAX_FILE_SIZE" value="5000000">
      <input type="file" name="upload_file" class="form-control-file" id="exampleFormControlFile1">
    </div>
    <a href="./home" class="btn btn-info float-right">ย้อนกลับ</a>
    <button type="submit" class="btn btn-primary" style="display:block; float:right;">อัพโหลด</button>
  </form>
</div>
