<?php include "./views/header.phtml"; ?>

<div class="container" style="width: 500px; padding-top: 4%;">

  <form method="post" enctype="multipart/form-data" action="./upload">
    <div class="form-group">
      <label for="recipient-name" class="col-form-label">ชื่อเอกสารหรือชื่อเรื่อง:</label>
      <input type="text" name="name_file" class="form-control" id="recipient-name" value="โครงการ A">
    </div>
    <div class="form-group">
      <label for="message-text" class="col-form-label">รายละเอียด:</label>
      <textarea class="form-control" name="describ" id="message-text">รายละเอียดของโครงการนี้...</textarea>
    </div>
    <div class="form-group">
      <label for="exampleFormControlFile1">ไฟล์ที่อัพโหลด</label>
      <input type="hidden" name="MAX_FILE_SIZE" value="100000">
      <input type="file" name="upload_file" class="form-control-file" id="exampleFormControlFile1">
    </div>
    <a href="./home" class="btn btn-info float-right">ย้อนกลับ</a>
    <button type="submit" class="btn btn-primary" style="display:block; float:right;">อัพโหลด</button>
  </form>
</div>
